export const ActionTypes = {
    SELL_BOOKS : "SELL_BOOKS",
    ADD_CART : "ADD_CART",
    // ONLY THE SELECTED CATAGORY
    CATAGORY: "CATAGORY",
    // ONLY THE SELECTED CATAGORY

    POPULARBOOKS : "POPULARBOOKS",
    // ONLY THE SELECTED CATAGORY
    AUTHOR: "AUTHOR",
}