export const ActionTypes = {
    // SELLING BOOKS
    SELL_BOOKS : "SELL_BOOKS",
    // ADDED TO CART 
    CART_BOOKS : "CART_BOOKS",
    // SELECTED BOOKS
    SELECTED_BOOKS : "SELECTED_BOOKS",
    // WHISTLIST
    WHISTLIST : "WHISTLIST",
    // ONLY THE SELECTED CATAGORY
    CATEGORY: "CATEGORY",
    // ONLY THE SELECTED BOOKS
    POPULARBOOKS : "POPULARBOOKS",
    // NEW USER DATA
    NEWUSER: "NEWUSER",
    // ONLY THE SELECTED CATAGORY
    AUTHOR: "AUTHOR",
    // Al USERS 
    ALLUSER : "ALLUSER",
    ALLPUBLISHER : "ALLPUBLISHER",
    ALLBOOKS : "ALLBOOKS",
    ALLAUTHORS : "ALLAUTHORS",
    MYORDER : "MYORDER",
    ALLORDERS : "ALLORDERS",
    MYPROFILE : "MYPROFILE",
    ORDERHISTORYS : "ORDERHISTORYS",
    CURRENT_CART : "CURRENT_CART"

}