export const ActionTypes = {
    // SELLING BOOKS
    SELL_BOOKS : "SELL_BOOKS",
    // ADDED TO CART 
    ADD_CART : "ADD_CART",
    // ONLY THE SELECTED CATAGORY
    CATEGORY: "CATEGORY",
    // ONLY THE SELECTED BOOKS
    POPULARBOOKS : "POPULARBOOKS",
    // NEW USER DATA
    NEWUSER: "NEWUSER",
    // ONLY THE SELECTED CATAGORY
    AUTHOR: "AUTHOR",
}